<a href="https://colab.research.google.com/github/vlasova-us/Python_public/blob/main/%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B5%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%C2%AB%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0_numpy_%D0%92%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D1%87%D0%B8%C2%BB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [ ]:
import numpy as np
number_input = int (input ("Введите число: "))

np.arange (0, number_input) [::-1]

Введите число: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [ ]:
number_input = int (input ("Введите число: "))

a = np.diag (np.arange (0, number_input) [::-1]) # создание диагональной матрицы с элементами от number_input до 0
print (a)
print ("Сумма диагонали: ", sum (np.diagonal(a) ) ) # сумма диагонали

Введите число: 9
[[8 0 0 0 0 0 0 0 0]
 [0 7 0 0 0 0 0 0 0]
 [0 0 6 0 0 0 0 0 0]
 [0 0 0 5 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]]
Сумма диагонали:  36


**Задание 3**
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3





In [ ]:
from numpy import linalg

left =  np.array ( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
right = np.array (   [4, 12, -3] )

# np.linalg.inv (left). dot (right)
linalg.solve (left, right)

# np.allclose (np.dot (left, linalg.solve (left, right)), right)

array([ 0.46666667,  3.84444444, -5.55555556])